# 1. Wczytywanie pliku

In [1]:
import pandas as pd

df = pd.read_csv('StudentsPerformance.csv')

# 2. Podgląd całości pliku

In [2]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# 3. Wyświetlanie częściowe

In [3]:
df.head(5)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [4]:
df["lunch"]

0          standard
1          standard
2          standard
3      free/reduced
4          standard
           ...
995        standard
996    free/reduced
997    free/reduced
998        standard
999    free/reduced
Name: lunch, Length: 1000, dtype: object

# 4. Wyświeltanie nazw kolumn (i przechowywanie)

In [5]:
columns = df.columns
columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

# 5. Sortowanie

In [6]:
df.sort_values(["math score"])

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
59,female,group C,some high school,free/reduced,none,0,17,10
980,female,group B,high school,free/reduced,none,8,24,23
17,female,group B,some high school,free/reduced,none,18,32,28
787,female,group B,some college,standard,none,19,38,32
145,female,group C,some college,free/reduced,none,22,39,33
...,...,...,...,...,...,...,...,...
625,male,group D,some college,standard,completed,100,97,99
623,male,group A,some college,standard,completed,100,96,86
451,female,group E,some college,standard,none,100,92,97
962,female,group E,associate's degree,standard,none,100,100,100
149,male,group E,associate's degree,free/reduced,completed,100,100,93

In [7]:
df.sort_values(["math score", "writing score"])

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
59,female,group C,some high school,free/reduced,none,0,17,10
980,female,group B,high school,free/reduced,none,8,24,23
17,female,group B,some high school,free/reduced,none,18,32,28
787,female,group B,some college,standard,none,19,38,32
145,female,group C,some college,free/reduced,none,22,39,33
...,...,...,...,...,...,...,...,...
451,female,group E,some college,standard,none,100,92,97
625,male,group D,some college,standard,completed,100,97,99
458,female,group E,bachelor's degree,standard,none,100,100,100
916,male,group E,bachelor's degree,standard,completed,100,100,100
962,female,group E,associate's degree,standard,none,100,100,100

In [8]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# 6. Tworzenie nowej kolumny

In [9]:
df['Total score'] = 0

In [10]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,0
2,female,group B,master's degree,standard,none,90,95,93,0
3,male,group A,associate's degree,free/reduced,none,47,57,44,0
4,male,group C,some college,standard,none,76,78,75,0
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,0
996,male,group C,high school,free/reduced,none,62,55,55,0
997,female,group C,high school,free/reduced,completed,59,71,65,0
998,female,group D,some college,standard,completed,68,78,77,0
999,female,group D,some college,free/reduced,none,77,86,86,0

# 7. Sumowanie elementów

In [11]:
df['total score'] = df.iloc[:, 5:8].sum(axis=1)

In [12]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total score,total score
0,female,group B,bachelor's degree,standard,none,72,72,74,0,218
1,female,group C,some college,standard,completed,69,90,88,0,247
2,female,group B,master's degree,standard,none,90,95,93,0,278
3,male,group A,associate's degree,free/reduced,none,47,57,44,0,148
4,male,group C,some college,standard,none,76,78,75,0,229
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,0,282
996,male,group C,high school,free/reduced,none,62,55,55,0,172
997,female,group C,high school,free/reduced,completed,59,71,65,0,195
998,female,group D,some college,standard,completed,68,78,77,0,223
999,female,group D,some college,free/reduced,none,77,86,86,0,249

# 8. Usuwanie kolumn (i wierszy)

In [13]:
df=df.drop(['Total score'], axis = 1)

In [14]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score
0,female,group B,bachelor's degree,standard,none,72,72,74,218
1,female,group C,some college,standard,completed,69,90,88,247
2,female,group B,master's degree,standard,none,90,95,93,278
3,male,group A,associate's degree,free/reduced,none,47,57,44,148
4,male,group C,some college,standard,none,76,78,75,229
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,282
996,male,group C,high school,free/reduced,none,62,55,55,172
997,female,group C,high school,free/reduced,completed,59,71,65,195
998,female,group D,some college,standard,completed,68,78,77,223
999,female,group D,some college,free/reduced,none,77,86,86,249

# 9. Proste filtorwanie

In [15]:
df.loc[df['lunch']=='standard']

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score
0,female,group B,bachelor's degree,standard,none,72,72,74,218
1,female,group C,some college,standard,completed,69,90,88,247
2,female,group B,master's degree,standard,none,90,95,93,278
4,male,group C,some college,standard,none,76,78,75,229
5,female,group B,associate's degree,standard,none,71,83,78,232
...,...,...,...,...,...,...,...,...,...
987,male,group E,some high school,standard,completed,81,75,76,232
991,female,group B,some high school,standard,completed,65,82,78,225
994,male,group A,high school,standard,none,63,63,62,188
995,female,group E,master's degree,standard,completed,88,99,95,282
998,female,group D,some college,standard,completed,68,78,77,223

In [16]:
df.loc[(df['lunch']=='standard') & (df['math score'] > 75)]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score
2,female,group B,master's degree,standard,none,90,95,93,278
4,male,group C,some college,standard,none,76,78,75,229
6,female,group B,some college,standard,completed,88,95,92,275
13,male,group A,some college,standard,completed,78,72,70,220
16,male,group C,high school,standard,none,88,89,86,263
...,...,...,...,...,...,...,...,...,...
981,male,group D,some high school,standard,none,81,78,78,237
982,male,group B,some high school,standard,completed,79,85,86,250
983,female,group A,some college,standard,completed,78,87,91,256
987,male,group E,some high school,standard,completed,81,75,76,232
995,female,group E,master's degree,standard,completed,88,99,95,282

In [17]:
df['count'] = 1

df.groupby(['race/ethnicity', 'parental level of education']).count()

                                            gender  lunch  \
race/ethnicity parental level of education
group A        associate's degree               14     14
               bachelor's degree                12     12
               high school                      18     18
               master's degree                   3      3
               some college                     18     18
               some high school                 24     24
group B        associate's degree               41     41
               bachelor's degree                20     20
               high school                      48     48
               master's degree                   6      6
               some college                     37     37
               some high school                 38     38
group C        associate's degree               78     78
               bachelor's degree                40     40
               high school                      64     64
               master's degree                  19     19
               some college                     69     69
               some high school                 49     49
group D        associate's degree               50     50
               bachelor's degree                28     28
               high school                      44     44
               master's degree                  23     23
               some college                     67     67
               some high school                 50     50
group E        associate's degree               39     39
               bachelor's degree                18     18
               high school                      22     22
               master's degree                   8      8
               some college                     35     35
               some high school                 18     18

                                            test preparation course  \
race/ethnicity parental level of education
group A        associate's degree                                14
               bachelor's degree                                 12
               high school                                       18
               master's degree                                    3
               some college                                      18
               some high school                                  24
group B        associate's degree                                41
               bachelor's degree                                 20
               high school                                       48
               master's degree                                    6
               some college                                      37
               some high school                                  38
group C        associate's degree                                78
               bachelor's degree                                 40
               high school                                       64
               master's degree                                   19
               some college                                      69
               some high school                                  49
group D        associate's degree                                50
               bachelor's degree                                 28
               high school                                       44
               master's degree                                   23
               some college                                      67
               some high school                                  50
group E        associate's degree                                39
               bachelor's degree                                 18
               high school                                       22
               master's degree                                    8
               some college                                      35
               some high school                                  18

                                            math score  reading score  \
race/ethnicity parental level of education
group A        associate's degree                   14             14
               bachelor's degree                    12             12
               high school                          18             18
               master's degree                       3              3
               some college                         18             18
               some high school                     24             24
group B        associate's degree                   41             41
               bachelor's degree                    20             20
               high school                          48             48
               master's degree                       6              6
               some college                         37             37
               some high school                     38             38
group C        associate's degree                   78             78
               bachelor's degree                    40             40
               high school                          64             64
               master's degree                      19             19
               some college                         69             69
               some high school                     49             49
group D        associate's degree                   50             50
               bachelor's degree                    28             28
               high school                          44             44
               master's degree                      23             23
               some college                         67             67
               some high school                     50             50
group E        associate's degree                   39             39
               bachelor's degree                    18             18
               high school                          22             22
               master's degree                       8              8
               some college                         35             35
               some high school                     18             18

                                            writing score  total score  count
race/ethnicity parental level of education
group A        associate's degree                      14           14     14
               bachelor's degree                       12           12     12
               high school                             18           18     18
               master's degree                          3            3      3
               some college                            18           18     18
               some high school                        24           24     24
group B        associate's degree                      41           41     41
               bachelor's degree                       20           20     20
               high school                             48           48     48
               master's degree                          6            6      6
               some college                            37           37     37
               some high school                        38           38     38
group C        associate's degree                      78           78     78
               bachelor's degree                       40           40     40
               high school                             64           64     64
               master's degree                         19           19     19
               some college                            69           69     69
               some high school                        49           49     49
group D        associate's degree                      50           50     50
               bachelor's degree                       28           28     28
               high school                             44           44     44
               master's degree                         23           23     23
               some college                            67           67     67
               some high school                        50           50     50
group E        associate's degree                      39           39     39
               bachelor's degree                       18           18     18
               high school                             22           22     22
               master's degree                          8            8      8
               some college                            35           35     35
               some high school                        18           18     18

In [18]:
df.groupby(['race/ethnicity', 'parental level of education']).count()['count']

race/ethnicity  parental level of education
group A         associate's degree             14
                bachelor's degree              12
                high school                    18
                master's degree                 3
                some college                   18
                some high school               24
group B         associate's degree             41
                bachelor's degree              20
                high school                    48
                master's degree                 6
                some college                   37
                some high school               38
group C         associate's degree             78
                bachelor's degree              40
                high school                    64
                master's degree                19
                some college                   69
                some high school               49
group D         associate's degree             50
                bachelor's degree              28
                high school                    44
                master's degree                23
                some college                   67
                some high school               50
group E         associate's degree             39
                bachelor's degree              18
                high school                    22
                master's degree                 8
                some college                   35
                some high school               18
Name: count, dtype: int64